### ISSUE TITLE
Opprett repository og sett opp Kanban

### ISSUE THREAD

**Issue by ToreMasoy** [ToreMasoy/Kurs_Tore#1]
## Users view

Title: **Tidsnok levering av meldinger iht. SLA med aktuelle mottakere, uavhengig av belastning på systemet **
User role(s): Avsender 
Users value statement(s): 
Fordi tid er avgjørende for mine kritiske forsendelser (f.eks eiendomshandel). De jeg sender til venter på informasjon fra meg før de får startet sine oppgaver eller besluttninger. Fordi jeg trenger at mine partnere har høy tillitt og er tilfreds med tjenesten. 

#### High level features (capabilities):
 * Overholde SLA for leveringstid, uavhengig av belastning på systemet 
#### Additional information
TBD

```[tasklist]
### Features
- [ ] Robusthet mot Denial of Service angrep
- [ ] Automatisk skalering av kapasitet ut fra belastning
- [ ] Separate kjøremiljøer (f.eks. for Politiet, slik at de ikke påvirkes av f-eks. Kartverket)
- [ ] Ytelsestesting ved utvikling
- [ ] Monitoring med dashboards og automatisk varsling
```

```[tasklist]
### Work items
  -[ ] Evaluer om dagens løsning for DOS-angrep er god nok
```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 26_
_Stage: Onboarding_
_ArchiConceptID: id-2e2196af63484a069954fa697971b033_
_GithubIssueID: I_kwDOIwEQMM5vYMwq_

- [ ] Test

**Comment by ToreMasoy** [comment]
- [x] Task 1
- [ ] Task 2
- [ ] Task 3
